# flake8: noqa
from .annotated import AnnotatedTests
from .asyncs import AsyncTests
from .augassign import AugAssignTests
from .binop import BinopTests
from .cached_property import CachedPropertyTests
from .checked_dict import CheckedDictTests
from .checked_list import CheckedListTests
from .classmethod import ClassMethodTests
from .compile import StaticCompilationTests
from .context_decorator import ContextDecoratorTests
from .dataclass import DataclassTests
from .decl_visitor import DeclarationVisitorTests
from .double import DoubleTests
from .dynamic_return import DynamicReturnTests
from .elide_type_checks import ElideTypeChecksTests
from .enum import StaticEnumTests
from .fields import StaticFieldTests
from .final import FinalTests
from .fstring import FStringTests
from .implicit_none_return import ImplicitNoneReturnTests
from .imports import ImportTests
from .inference import InferenceTests
from .invoke import InvokeTests
from .lint import LintTests
from .literals import LiteralsTests
from .module import ModuleTests
from .native import NativeDecoratorTests
from .non_static_inheritance import NonStaticInheritanceTests
from .obj_creation import StaticObjCreationTests
from .overrides import OverridesTests
from .patch import StaticPatchTests
from .perf_lint import PerfLintTests
from .primitives import PrimitivesTests
from .property import PropertyTests
from .protocol import ProtocolTests
from .readonly import ReadonlyTests
from .refine_fields import RefineFieldsTests
from .return_cast_insertion import ReturnCastInsertionTests
from .runtime import StaticRuntimeTests
from .sequence import SequenceTests

from .slots_with_default import SlotsWithDefaultTests
from .staticmod import StaticModuleTests
from .subclass import SubclassTests
from .super import SuperTests
from .top_level import TopLevelTests
from .typed_dict import TypedDictTests
from .union import UnionCompilationTests
from .variadic_arg import VariadicArgTests
from .walrus_operator import WalrusOperatorTests
