from .array import ArrayTests
from .augassign import AugAssignTests
from .binop import BinopTests
from .cached_property import CachedPropertyTests
from .checked_list import CheckedListTests
from .classmethod import ClassMethodTests
from .context_decorator import ContextDecoratorTests
from .decl_visitor import DeclarationVisitorTests
from .dynamic_return import DynamicReturnTests
from .elide_type_checks import ElideTypeChecksTests
from .enum import StaticEnumTests
from .fields import StaticFieldTests
from .final import FinalTests
from .fstring import FStringTests
from .imports import ImportTests
from .inference import InferenceTests
from .lint import LintTests
from .module import ModuleTests
from .non_static_inheritance import NonStaticInheritanceTests
from .obj_creation import StaticObjCreationTests
from .patch import StaticPatchTests
from .primitives import PrimitivesTests
from .property import PropertyTests
from .return_cast_insertion import ReturnCastInsertionTests
from .sequence import SequenceTests
from .slots_with_default import SlotsWithDefaultTests
from .subclass import SubclassTests
from .tests import StaticCompilationTests, StaticRuntimeTests
from .top_level import TopLevelTests
from .union import UnionCompilationTests
from .variadic_arg import VariadicArgTests
from .walrus_operator import WalrusOperatorTests
