from typing import Any

class spamobj:
    def error(self) -> raises: ...
    def getint(self) -> i: ...
    def getint16(self) -> i: ...
    def getint32(self) -> i: ...
    def getint8(self) -> i: ...
    def getstate(self) -> state: ...
    def getstr(self) -> s: ...
    def getuint16(self) -> i: ...
    def getuint32(self) -> i: ...
    def getuint64(self) -> i: ...
    def getuint8(self) -> i: ...
    def setint(self, i) -> Any: ...
    def setint16(self, i) -> Any: ...
    def setint32(self, i) -> Any: ...
    def setint8(self, i) -> Any: ...
    def setstate(self, state) -> Any: ...
    def setstate_untyped(self, *args, **kwargs) -> Any: ...
    def setstateoptional(self, *args, **kwargs) -> Any: ...
    def setstr(self, s) -> Any: ...
    def setuint16(self, i) -> Any: ...
    def setuint32(self, i) -> Any: ...
    def setuint64(self, i) -> Any: ...
    def setuint8(self, i) -> Any: ...
    def twoargs(self, s) -> Any: ...
    @classmethod
    def __class_getitem__(cls, *args, **kwargs) -> Any: ...

def bar(*args, **kwargs) -> Any: ...
def foo(*args, **kwargs) -> Any: ...
def neg(*args, **kwargs) -> Any: ...
def traverse_heap(*args, **kwargs) -> Any: ...
def unsafe_change_type(*args, **kwargs) -> Any: ...
