/* Copyright (c) Facebook, Inc. and its affiliates. (http://www.facebook.com) */
/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* PyDTrace_FUNCTION_ENTRY ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define PyDTrace_FUNCTION_ENTRY_ENABLED() __builtin_expect (function__entry_semaphore, 0)
#define python_function__entry_semaphore function__entry_semaphore
#else
#define PyDTrace_FUNCTION_ENTRY_ENABLED() __builtin_expect (python_function__entry_semaphore, 0)
#endif
__extension__ extern unsigned short python_function__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_FUNCTION_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (python, function__entry, arg1, arg2, arg3)

/* PyDTrace_FUNCTION_RETURN ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define PyDTrace_FUNCTION_RETURN_ENABLED() __builtin_expect (function__return_semaphore, 0)
#define python_function__return_semaphore function__return_semaphore
#else
#define PyDTrace_FUNCTION_RETURN_ENABLED() __builtin_expect (python_function__return_semaphore, 0)
#endif
__extension__ extern unsigned short python_function__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_FUNCTION_RETURN(arg1, arg2, arg3) \
DTRACE_PROBE3 (python, function__return, arg1, arg2, arg3)

/* PyDTrace_INSTANCE_NEW_START ( const char *, const char * ) */
#if defined STAP_SDT_V1
#define PyDTrace_INSTANCE_NEW_START_ENABLED() __builtin_expect (instance__new__start_semaphore, 0)
#define python_instance__new__start_semaphore instance__new__start_semaphore
#else
#define PyDTrace_INSTANCE_NEW_START_ENABLED() __builtin_expect (python_instance__new__start_semaphore, 0)
#endif
__extension__ extern unsigned short python_instance__new__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_INSTANCE_NEW_START(arg1, arg2) \
DTRACE_PROBE2 (python, instance__new__start, arg1, arg2)

/* PyDTrace_INSTANCE_NEW_DONE ( const char *, const char * ) */
#if defined STAP_SDT_V1
#define PyDTrace_INSTANCE_NEW_DONE_ENABLED() __builtin_expect (instance__new__done_semaphore, 0)
#define python_instance__new__done_semaphore instance__new__done_semaphore
#else
#define PyDTrace_INSTANCE_NEW_DONE_ENABLED() __builtin_expect (python_instance__new__done_semaphore, 0)
#endif
__extension__ extern unsigned short python_instance__new__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_INSTANCE_NEW_DONE(arg1, arg2) \
DTRACE_PROBE2 (python, instance__new__done, arg1, arg2)

/* PyDTrace_INSTANCE_DELETE_START ( const char *, const char * ) */
#if defined STAP_SDT_V1
#define PyDTrace_INSTANCE_DELETE_START_ENABLED() __builtin_expect (instance__delete__start_semaphore, 0)
#define python_instance__delete__start_semaphore instance__delete__start_semaphore
#else
#define PyDTrace_INSTANCE_DELETE_START_ENABLED() __builtin_expect (python_instance__delete__start_semaphore, 0)
#endif
__extension__ extern unsigned short python_instance__delete__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_INSTANCE_DELETE_START(arg1, arg2) \
DTRACE_PROBE2 (python, instance__delete__start, arg1, arg2)

/* PyDTrace_INSTANCE_DELETE_DONE ( const char *, const char * ) */
#if defined STAP_SDT_V1
#define PyDTrace_INSTANCE_DELETE_DONE_ENABLED() __builtin_expect (instance__delete__done_semaphore, 0)
#define python_instance__delete__done_semaphore instance__delete__done_semaphore
#else
#define PyDTrace_INSTANCE_DELETE_DONE_ENABLED() __builtin_expect (python_instance__delete__done_semaphore, 0)
#endif
__extension__ extern unsigned short python_instance__delete__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_INSTANCE_DELETE_DONE(arg1, arg2) \
DTRACE_PROBE2 (python, instance__delete__done, arg1, arg2)

/* PyDTrace_LINE ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define PyDTrace_LINE_ENABLED() __builtin_expect (line_semaphore, 0)
#define python_line_semaphore line_semaphore
#else
#define PyDTrace_LINE_ENABLED() __builtin_expect (python_line_semaphore, 0)
#endif
__extension__ extern unsigned short python_line_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_LINE(arg1, arg2, arg3) \
DTRACE_PROBE3 (python, line, arg1, arg2, arg3)

/* PyDTrace_INSTRUCTION ( uint64_t, uint64_t, uint16_t, uint16_t *, uint16_t * ) */
#if defined STAP_SDT_V1
#define PyDTrace_INSTRUCTION_ENABLED() __builtin_expect (instruction_semaphore, 0)
#define python_instruction_semaphore instruction_semaphore
#else
#define PyDTrace_INSTRUCTION_ENABLED() __builtin_expect (python_instruction_semaphore, 0)
#endif
__extension__ extern unsigned short python_instruction_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_INSTRUCTION(arg1, arg2, arg3, arg4, arg5) \
DTRACE_PROBE5 (python, instruction, arg1, arg2, arg3, arg4, arg5)

/* PyDTrace_GC_START ( int ) */
#if defined STAP_SDT_V1
#define PyDTrace_GC_START_ENABLED() __builtin_expect (gc__start_semaphore, 0)
#define python_gc__start_semaphore gc__start_semaphore
#else
#define PyDTrace_GC_START_ENABLED() __builtin_expect (python_gc__start_semaphore, 0)
#endif
__extension__ extern unsigned short python_gc__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_GC_START(arg1) \
DTRACE_PROBE1 (python, gc__start, arg1)

/* PyDTrace_GC_DONE ( long ) */
#if defined STAP_SDT_V1
#define PyDTrace_GC_DONE_ENABLED() __builtin_expect (gc__done_semaphore, 0)
#define python_gc__done_semaphore gc__done_semaphore
#else
#define PyDTrace_GC_DONE_ENABLED() __builtin_expect (python_gc__done_semaphore, 0)
#endif
__extension__ extern unsigned short python_gc__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_GC_DONE(arg1) \
DTRACE_PROBE1 (python, gc__done, arg1)

/* PyDTrace_IMPORT_FIND_LOAD_START ( const char * ) */
#if defined STAP_SDT_V1
#define PyDTrace_IMPORT_FIND_LOAD_START_ENABLED() __builtin_expect (import__find__load__start_semaphore, 0)
#define python_import__find__load__start_semaphore import__find__load__start_semaphore
#else
#define PyDTrace_IMPORT_FIND_LOAD_START_ENABLED() __builtin_expect (python_import__find__load__start_semaphore, 0)
#endif
__extension__ extern unsigned short python_import__find__load__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_IMPORT_FIND_LOAD_START(arg1) \
DTRACE_PROBE1 (python, import__find__load__start, arg1)

/* PyDTrace_IMPORT_FIND_LOAD_DONE ( const char *, int ) */
#if defined STAP_SDT_V1
#define PyDTrace_IMPORT_FIND_LOAD_DONE_ENABLED() __builtin_expect (import__find__load__done_semaphore, 0)
#define python_import__find__load__done_semaphore import__find__load__done_semaphore
#else
#define PyDTrace_IMPORT_FIND_LOAD_DONE_ENABLED() __builtin_expect (python_import__find__load__done_semaphore, 0)
#endif
__extension__ extern unsigned short python_import__find__load__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PyDTrace_IMPORT_FIND_LOAD_DONE(arg1, arg2) \
DTRACE_PROBE2 (python, import__find__load__done, arg1, arg2)

