name: TestsMSI

on:
  workflow_call:
    inputs:
      arch:
        description: CPU architecture
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: installer for ${{ inputs.arch }}
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      IncludeFreethreaded: true
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython installer
      run: .\Tools\msi\build.bat --doc -${{ inputs.arch }}
